services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $isDebug: '%kernel.debug%'

    Torr\Assets\:
        resource: ../src/*
        exclude: ../src/{Exception,AssetsBundle.php}

    Torr\Assets\Routing\AssetsRouteLoader:
        tags: [routing.loader]

    Torr\Assets\File\FileTypeRegistry:
        $fileTypes: !tagged_iterator 'assets.file-type'

    Torr\Assets\Storage\AssetStorage:
        $publicDir: '%kernel.project_dir%/public'
