services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Torr\Assets\:
        resource: ../src/*
        exclude: ../src/{Exception,AssetsBundle.php}

    Torr\Assets\Routing\AssetsRouteLoader:
        tags: [routing.loader]

    Torr\Assets\Storage\AssetDumper:
        $publicDir: '%kernel.project_dir%/public'
